name: CDK Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r backend/requirements.txt
          pip install aws-cdk-lib constructs
          npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: DEBUG Print Env Var
        run: |
          echo "Attempting to print STRIPE_TEST_SECRET_KEY:"
          echo "Value: [${{ env.STRIPE_TEST_SECRET_KEY }}]"
          if [ -z "${{ env.STRIPE_TEST_SECRET_KEY }}" ]; then
            echo "ERROR: STRIPE_TEST_SECRET_KEY appears empty or unset!"
          else
            echo "OK: STRIPE_TEST_SECRET_KEY seems to have a value."
          fi
        env:
          STRIPE_TEST_SECRET_KEY: ${{ secrets.STRIPE_TEST_SECRET_KEY }}

      - name: CDK Bootstrap
        run: cdk bootstrap
        env:
          STRIPE_TEST_SECRET_KEY: ${{ secrets.STRIPE_TEST_SECRET_KEY }}
          STRIPE_TEST_PUBLISHABLE_KEY: ${{ secrets.STRIPE_TEST_PUBLISHABLE_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          PRODIGI_SANDBOX_API_KEY: ${{ secrets.PRODIGI_SANDBOX_API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          SUCCESS_URL: 'https://hansenhomeai.github.io/success'
          CANCEL_URL: 'https://hansenhomeai.github.io/cancel'

      - name: CDK Deploy
        run: cdk deploy --require-approval never
        env:
          STRIPE_TEST_SECRET_KEY: ${{ secrets.STRIPE_TEST_SECRET_KEY }}
          STRIPE_TEST_PUBLISHABLE_KEY: ${{ secrets.STRIPE_TEST_PUBLISHABLE_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          PRODIGI_SANDBOX_API_KEY: ${{ secrets.PRODIGI_SANDBOX_API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          SUCCESS_URL: 'https://hansenhomeai.github.io/success'
          CANCEL_URL: 'https://hansenhomeai.github.io/cancel' 