name: CDK Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r backend/requirements.txt
          pip install aws-cdk-lib constructs

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: CDK Bootstrap
        run: cdk bootstrap
        env:
          CDK_DEFAULT_REGION: us-west-2
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: CDK Deploy
        run: cdk deploy --require-approval never
        env:
          CDK_DEFAULT_REGION: us-west-2
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          PRODIGI_API_KEY: ${{ secrets.PRODIGI_API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          SUCCESS_URL: ${{ secrets.SUCCESS_URL }}
          CANCEL_URL: ${{ secrets.CANCEL_URL }} 